pipeline {
  agent any

  tools {
    maven 'maven 3.6.1'
  }
  
  stages {
    stage("build") {
      echo "Compiling app!"
      dir('worker') {
        sh 'mvn compile'
      }
    }

    stage("test") {
      echo 'Running unit tests on worker app'
    }

    stage("package") {
      echo 'Packaging worker app'
    }
  }

  post {
    always {
      echo 'Building multibranch pipeline for worker is completed...'
    }
  }
}
